CREATE TABLE benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    benefit_type VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    discount_percent INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_benefits_subscription_id FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)
);

CREATE INDEX idx_benefits_subscription_id ON benefits (subscription_id);
