INSERT INTO orders (id, user_id, amount, created_at, updated_at, order_status, version)
VALUES
    (1, 1, 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (2, 1, 120, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 'PENDING_PAYMENT', 0),
    (3, 2, 800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (4, 2, 450, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (5, 2, 300, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP, 'CANCELLED', 0),
    (6, 3, 2200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (7, 3, 1800, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 'IN_TRANSIT', 0),
    (8, 3, 900, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 'CONFIRMED', 0),
    (9, 4, 150, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 'FAILED', 0),
    (10, 4, 75, CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (11, 5, 3500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (12, 5, 2700, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 'DELIVERED', 0),
    (13, 5, 400, CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 'CANCELLED', 0);

SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT MAX(id) FROM orders));
