INSERT INTO memberships (
    id, user_id, subscription_id, created_at, expire_at, updated_at, membership_status, version
)
VALUES
    (1, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '36500 days', CURRENT_TIMESTAMP, 'ACTIVE', 0),
    (2, 2, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '30 days', CURRENT_TIMESTAMP, 'ACTIVE', 0),
    (3, 3, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '365 days', CURRENT_TIMESTAMP, 'ACTIVE', 0),
    (4, 4, 6, CURRENT_TIMESTAMP - INTERVAL '400 days', CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP, 'CANCELLED', 0),
    (5, 5, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '90 days', CURRENT_TIMESTAMP, 'ACTIVE', 0),
    (6, 5, 1, CURRENT_TIMESTAMP - INTERVAL '200 days', CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP, 'EXPIRED', 0);

SELECT setval(pg_get_serial_sequence('memberships', 'id'), (SELECT MAX(id) FROM memberships));
