CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    user_account_status VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);
