CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_name VARCHAR(100) NOT NULL,
    subscription_tier VARCHAR(255) NOT NULL,
    subscription_plan VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    subscription_status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);
