CREATE TABLE memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    expire_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    membership_status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_memberships_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_memberships_subscription_id FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)
);

CREATE INDEX idx_memberships_user_id ON memberships (user_id);
CREATE INDEX idx_memberships_subscription_id ON memberships (subscription_id);
